### ISSUE TITLE
Darwin / ARM64 Compilation Error

### ISSUE THREAD

**Issue by freb** [azr/phash#7]
I've reviewed the referenced code and can't imagine why I'm getting a compilation error. Perhaps you can help.

I'm compiling to `GOOS=darwin`, `GOARCH=arm64` on  Linux system. Here is the command and output:

~~~bash
> $ GOOS=darwin GOARCH=arm64 go build
# github.com/azr/phash/geometry/triangle
../../../go/pkg/mod/github.com/azr/phash@v0.2.0/geometry/triangle/triangle.go:34:12: internal compiler error: '(*Triangle).Contains': InvertFlags should never make it to codegen v119 = InvertFlags <flags> v45

Please file a bug report including a short program that triggers the error.
https://go.dev/issue/new
~~~

**Comment by freb** [comment]
I just discovered the error seems to be restricted to Go 1.21.

**Comment by TheRook** [comment]
I am also getting this error:
/phash@v0.2.0/geometry/triangle/triangle.go:38:12: internal compiler error: '(*Triangle).HasPoint': InvertFlags should never make it to codegen v100 = InvertFlags <flags> v123

**Comment by azr** [comment]
Thanks for this !

**Comment by azr** [comment]
closing, as this worked for me
